[package]
name = "cmaes"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
nalgebra = "0.30.1"
num-traits = "0.2.14"
statrs = "0.15.0"
rayon = "1.5.1"

[dev-dependencies]
assert_approx_eq = "1.1.0"
